/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// InlineObject struct for InlineObject
type InlineObject struct {
	Email         string `json:"email,omitempty"`
	Pass          string `json:"pass,omitempty"`
	FromAuthorize string `json:"from_authorize,omitempty"`
	CliToken      string `json:"cli_token,omitempty"`
	CleverFlavor  string `json:"clever_flavor,omitempty"`
	OauthToken    string `json:"oauth_token,omitempty"`
}
