/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// InvoiceLineRendering struct for InvoiceLineRendering
type InvoiceLineRendering struct {
	Description    string  `json:"description,omitempty"`
	SubDescription string  `json:"subDescription,omitempty"`
	Pack           string  `json:"pack,omitempty"`
	VAT            float32 `json:"VAT,omitempty"`
	Price          float32 `json:"price,omitempty"`
}
