/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clevercloud

import (
	"encoding/json"
)

// WannabeAvatarSource struct for WannabeAvatarSource
type WannabeAvatarSource struct {
	Source *string `json:"source,omitempty"`
}

// NewWannabeAvatarSource instantiates a new WannabeAvatarSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWannabeAvatarSource() *WannabeAvatarSource {
	this := WannabeAvatarSource{}
	return &this
}

// NewWannabeAvatarSourceWithDefaults instantiates a new WannabeAvatarSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWannabeAvatarSourceWithDefaults() *WannabeAvatarSource {
	this := WannabeAvatarSource{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *WannabeAvatarSource) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAvatarSource) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *WannabeAvatarSource) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *WannabeAvatarSource) SetSource(v string) {
	o.Source = &v
}

func (o WannabeAvatarSource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	return json.Marshal(toSerialize)
}

type NullableWannabeAvatarSource struct {
	value *WannabeAvatarSource
	isSet bool
}

func (v NullableWannabeAvatarSource) Get() *WannabeAvatarSource {
	return v.value
}

func (v *NullableWannabeAvatarSource) Set(val *WannabeAvatarSource) {
	v.value = val
	v.isSet = true
}

func (v NullableWannabeAvatarSource) IsSet() bool {
	return v.isSet
}

func (v *NullableWannabeAvatarSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWannabeAvatarSource(val *WannabeAvatarSource) *NullableWannabeAvatarSource {
	return &NullableWannabeAvatarSource{value: val, isSet: true}
}

func (v NullableWannabeAvatarSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWannabeAvatarSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
