/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// WannabeAuthorization struct for WannabeAuthorization
type WannabeAuthorization struct {
	Verb          string `json:"verb,omitempty"`
	Uri           string `json:"uri,omitempty"`
	Authorization string `json:"authorization,omitempty"`
	Payload       string `json:"payload,omitempty"`
	Nonce         string `json:"nonce,omitempty"`
	Mac           string `json:"mac,omitempty"`
}
