/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// WannabeAddonProviderApi struct for WannabeAddonProviderApi
type WannabeAddonProviderApi struct {
	ConfigVars []string                   `json:"config_vars,omitempty"`
	Password   string                     `json:"password,omitempty"`
	SsoSalt    string                     `json:"sso_salt,omitempty"`
	Regions    []string                   `json:"regions,omitempty"`
	Production WannabeAddonProviderApiUrl `json:"production,omitempty"`
	Test       WannabeAddonProviderApiUrl `json:"test,omitempty"`
}
