/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clevercloud

import (
	"encoding/json"
)

// WannabeMaxCredits struct for WannabeMaxCredits
type WannabeMaxCredits struct {
	Max *float32 `json:"max,omitempty"`
}

// NewWannabeMaxCredits instantiates a new WannabeMaxCredits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWannabeMaxCredits() *WannabeMaxCredits {
	this := WannabeMaxCredits{}
	return &this
}

// NewWannabeMaxCreditsWithDefaults instantiates a new WannabeMaxCredits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWannabeMaxCreditsWithDefaults() *WannabeMaxCredits {
	this := WannabeMaxCredits{}
	return &this
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *WannabeMaxCredits) GetMax() float32 {
	if o == nil || o.Max == nil {
		var ret float32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeMaxCredits) GetMaxOk() (*float32, bool) {
	if o == nil || o.Max == nil {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *WannabeMaxCredits) HasMax() bool {
	if o != nil && o.Max != nil {
		return true
	}

	return false
}

// SetMax gets a reference to the given float32 and assigns it to the Max field.
func (o *WannabeMaxCredits) SetMax(v float32) {
	o.Max = &v
}

func (o WannabeMaxCredits) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Max != nil {
		toSerialize["max"] = o.Max
	}
	return json.Marshal(toSerialize)
}

type NullableWannabeMaxCredits struct {
	value *WannabeMaxCredits
	isSet bool
}

func (v NullableWannabeMaxCredits) Get() *WannabeMaxCredits {
	return v.value
}

func (v *NullableWannabeMaxCredits) Set(val *WannabeMaxCredits) {
	v.value = val
	v.isSet = true
}

func (v NullableWannabeMaxCredits) IsSet() bool {
	return v.isSet
}

func (v *NullableWannabeMaxCredits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWannabeMaxCredits(val *WannabeMaxCredits) *NullableWannabeMaxCredits {
	return &NullableWannabeMaxCredits{value: val, isSet: true}
}

func (v NullableWannabeMaxCredits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWannabeMaxCredits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
