/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// WannabeMember struct for WannabeMember
type WannabeMember struct {
	Role  string `json:"role,omitempty"`
	Job   string `json:"job,omitempty"`
	Email string `json:"email,omitempty"`
}
