/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// PaymentProviderSelection struct for PaymentProviderSelection
type PaymentProviderSelection struct {
	Provider string `json:"provider,omitempty"`
}
