/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// InvoiceRendering struct for InvoiceRendering
type InvoiceRendering struct {
	Id                 string                 `json:"id,omitempty"`
	Number             string                 `json:"number,omitempty"`
	Status             string                 `json:"status,omitempty"`
	EmissionDate       string                 `json:"emissionDate,omitempty"`
	PaymentDate        string                 `json:"paymentDate,omitempty"`
	Name               string                 `json:"name,omitempty"`
	Company            string                 `json:"company,omitempty"`
	Target             string                 `json:"target,omitempty"`
	Address            string                 `json:"address,omitempty"`
	ZipCode            string                 `json:"zipCode,omitempty"`
	City               string                 `json:"city,omitempty"`
	Country            string                 `json:"country,omitempty"`
	CountryCode        string                 `json:"countryCode,omitempty"`
	VatNumber          string                 `json:"vatNumber,omitempty"`
	FromSubscription   bool                   `json:"fromSubscription,omitempty"`
	Lines              []InvoiceLineRendering `json:"lines,omitempty"`
	OriginalTotal      float32                `json:"originalTotal,omitempty"`
	TotalHT            float32                `json:"totalHT,omitempty"`
	TotalVAT           float32                `json:"totalVAT,omitempty"`
	TotalTTC           float32                `json:"totalTTC,omitempty"`
	Type               string                 `json:"type,omitempty"`
	PayingUser         OrganisationMemberView `json:"payingUser,omitempty"`
	ErrorCode          string                 `json:"errorCode,omitempty"`
	ErrorShortMsg      string                 `json:"errorShortMsg,omitempty"`
	ErrorLongMsg       string                 `json:"errorLongMsg,omitempty"`
	Token              string                 `json:"token,omitempty"`
	TargetId           string                 `json:"targetId,omitempty"`
	ForId              string                 `json:"forId,omitempty"`
	CustomerOrderId    string                 `json:"customerOrderId,omitempty"`
	CustomerCostCenter string                 `json:"customerCostCenter,omitempty"`
	VatRate            float32                `json:"vatRate,omitempty"`
	PayWhen            string                 `json:"payWhen,omitempty"`
}
