/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clevercloud

import (
	"encoding/json"
)

// GithubWebhookRepository struct for GithubWebhookRepository
type GithubWebhookRepository struct {
	Id *string `json:"id,omitempty"`
}

// NewGithubWebhookRepository instantiates a new GithubWebhookRepository object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubWebhookRepository() *GithubWebhookRepository {
	this := GithubWebhookRepository{}
	return &this
}

// NewGithubWebhookRepositoryWithDefaults instantiates a new GithubWebhookRepository object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubWebhookRepositoryWithDefaults() *GithubWebhookRepository {
	this := GithubWebhookRepository{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GithubWebhookRepository) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubWebhookRepository) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GithubWebhookRepository) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GithubWebhookRepository) SetId(v string) {
	o.Id = &v
}

func (o GithubWebhookRepository) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableGithubWebhookRepository struct {
	value *GithubWebhookRepository
	isSet bool
}

func (v NullableGithubWebhookRepository) Get() *GithubWebhookRepository {
	return v.value
}

func (v *NullableGithubWebhookRepository) Set(val *GithubWebhookRepository) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubWebhookRepository) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubWebhookRepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubWebhookRepository(val *GithubWebhookRepository) *NullableGithubWebhookRepository {
	return &NullableGithubWebhookRepository{value: val, isSet: true}
}

func (v NullableGithubWebhookRepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubWebhookRepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
