/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// AddonPlanView struct for AddonPlanView
type AddonPlanView struct {
	Id       string                     `json:"id,omitempty"`
	Name     string                     `json:"name,omitempty"`
	Slug     string                     `json:"slug,omitempty"`
	Price    float32                    `json:"price,omitempty"`
	PriceId  string                     `json:"price_id,omitempty"`
	Features []AddonFeatureInstanceView `json:"features,omitempty"`
	Zones    []string                   `json:"zones,omitempty"`
}
