/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// InstanceVariantView struct for InstanceVariantView
type InstanceVariantView struct {
	Id         string `json:"id,omitempty"`
	Slug       string `json:"slug,omitempty"`
	Name       string `json:"name,omitempty"`
	DeployType string `json:"deployType,omitempty"`
	Logo       string `json:"logo,omitempty"`
}
