/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clevercloud

import (
	"encoding/json"
)

// OrganisationMemberView struct for OrganisationMemberView
type OrganisationMemberView struct {
	Member *OrganisationMemberUserView `json:"member,omitempty"`
	Role   *string                     `json:"role,omitempty"`
	Job    *string                     `json:"job,omitempty"`
}

// NewOrganisationMemberView instantiates a new OrganisationMemberView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganisationMemberView() *OrganisationMemberView {
	this := OrganisationMemberView{}
	return &this
}

// NewOrganisationMemberViewWithDefaults instantiates a new OrganisationMemberView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganisationMemberViewWithDefaults() *OrganisationMemberView {
	this := OrganisationMemberView{}
	return &this
}

// GetMember returns the Member field value if set, zero value otherwise.
func (o *OrganisationMemberView) GetMember() OrganisationMemberUserView {
	if o == nil || o.Member == nil {
		var ret OrganisationMemberUserView
		return ret
	}
	return *o.Member
}

// GetMemberOk returns a tuple with the Member field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationMemberView) GetMemberOk() (*OrganisationMemberUserView, bool) {
	if o == nil || o.Member == nil {
		return nil, false
	}
	return o.Member, true
}

// HasMember returns a boolean if a field has been set.
func (o *OrganisationMemberView) HasMember() bool {
	if o != nil && o.Member != nil {
		return true
	}

	return false
}

// SetMember gets a reference to the given OrganisationMemberUserView and assigns it to the Member field.
func (o *OrganisationMemberView) SetMember(v OrganisationMemberUserView) {
	o.Member = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *OrganisationMemberView) GetRole() string {
	if o == nil || o.Role == nil {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationMemberView) GetRoleOk() (*string, bool) {
	if o == nil || o.Role == nil {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *OrganisationMemberView) HasRole() bool {
	if o != nil && o.Role != nil {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *OrganisationMemberView) SetRole(v string) {
	o.Role = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *OrganisationMemberView) GetJob() string {
	if o == nil || o.Job == nil {
		var ret string
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationMemberView) GetJobOk() (*string, bool) {
	if o == nil || o.Job == nil {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *OrganisationMemberView) HasJob() bool {
	if o != nil && o.Job != nil {
		return true
	}

	return false
}

// SetJob gets a reference to the given string and assigns it to the Job field.
func (o *OrganisationMemberView) SetJob(v string) {
	o.Job = &v
}

func (o OrganisationMemberView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Member != nil {
		toSerialize["member"] = o.Member
	}
	if o.Role != nil {
		toSerialize["role"] = o.Role
	}
	if o.Job != nil {
		toSerialize["job"] = o.Job
	}
	return json.Marshal(toSerialize)
}

type NullableOrganisationMemberView struct {
	value *OrganisationMemberView
	isSet bool
}

func (v NullableOrganisationMemberView) Get() *OrganisationMemberView {
	return v.value
}

func (v *NullableOrganisationMemberView) Set(val *OrganisationMemberView) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganisationMemberView) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganisationMemberView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganisationMemberView(val *OrganisationMemberView) *NullableOrganisationMemberView {
	return &NullableOrganisationMemberView{value: val, isSet: true}
}

func (v NullableOrganisationMemberView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganisationMemberView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
