/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// AddonSsoData struct for AddonSsoData
type AddonSsoData struct {
	Url       string `json:"url,omitempty"`
	Id        string `json:"id,omitempty"`
	Timestamp int64  `json:"timestamp,omitempty"`
	Token     string `json:"token,omitempty"`
	Email     string `json:"email,omitempty"`
	NavData   string `json:"nav-data,omitempty"`
}
