/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// OrganisationSummary struct for OrganisationSummary
type OrganisationSummary struct {
	Id               string                  `json:"id,omitempty"`
	Name             string                  `json:"name,omitempty"`
	Avatar           string                  `json:"avatar,omitempty"`
	Applications     []ApplicationSummary    `json:"applications,omitempty"`
	Addons           []AddonSummary          `json:"addons,omitempty"`
	Consumers        []OAuth1ConsumerSummary `json:"consumers,omitempty"`
	Role             string                  `json:"role,omitempty"`
	Providers        []ProviderSummary       `json:"providers,omitempty"`
	VatState         string                  `json:"vatState,omitempty"`
	CanPay           bool                    `json:"canPay,omitempty"`
	CanSEPA          bool                    `json:"canSEPA,omitempty"`
	CleverEnterprise bool                    `json:"cleverEnterprise,omitempty"`
	EmergencyNumber  string                  `json:"emergencyNumber,omitempty"`
}
