/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// DeploymentView struct for DeploymentView
type DeploymentView struct {
	Id        int32  `json:"id,omitempty"`
	Uuid      string `json:"uuid,omitempty"`
	Date      int64  `json:"date,omitempty"`
	State     string `json:"state,omitempty"`
	Action    string `json:"action,omitempty"`
	Commit    string `json:"commit,omitempty"`
	Cause     string `json:"cause,omitempty"`
	Instances int32  `json:"instances,omitempty"`
	Author    Author `json:"author,omitempty"`
}
