/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// SuperNovaInstanceMap struct for SuperNovaInstanceMap
type SuperNovaInstanceMap struct {
	Empty bool `json:"empty,omitempty"`
}
