/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clevercloud

import (
	"encoding/json"
)

// WannabeAddonConfig struct for WannabeAddonConfig
type WannabeAddonConfig struct {
	Config *map[string]string `json:"config,omitempty"`
}

// NewWannabeAddonConfig instantiates a new WannabeAddonConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWannabeAddonConfig() *WannabeAddonConfig {
	this := WannabeAddonConfig{}
	return &this
}

// NewWannabeAddonConfigWithDefaults instantiates a new WannabeAddonConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWannabeAddonConfigWithDefaults() *WannabeAddonConfig {
	this := WannabeAddonConfig{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *WannabeAddonConfig) GetConfig() map[string]string {
	if o == nil || o.Config == nil {
		var ret map[string]string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonConfig) GetConfigOk() (*map[string]string, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *WannabeAddonConfig) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]string and assigns it to the Config field.
func (o *WannabeAddonConfig) SetConfig(v map[string]string) {
	o.Config = &v
}

func (o WannabeAddonConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableWannabeAddonConfig struct {
	value *WannabeAddonConfig
	isSet bool
}

func (v NullableWannabeAddonConfig) Get() *WannabeAddonConfig {
	return v.value
}

func (v *NullableWannabeAddonConfig) Set(val *WannabeAddonConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableWannabeAddonConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableWannabeAddonConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWannabeAddonConfig(val *WannabeAddonConfig) *NullableWannabeAddonConfig {
	return &NullableWannabeAddonConfig{value: val, isSet: true}
}

func (v NullableWannabeAddonConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWannabeAddonConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
