/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// OAuthRightsView struct for OAuthRightsView
type OAuthRightsView struct {
	Almighty                                 bool `json:"almighty,omitempty"`
	AccessOrganisations                      bool `json:"access_organisations,omitempty"`
	ManageOrganisations                      bool `json:"manage_organisations,omitempty"`
	ManageOrganisationsServices              bool `json:"manage_organisations_services,omitempty"`
	ManageOrganisationsApplications          bool `json:"manage_organisations_applications,omitempty"`
	ManageOrganisationsMembers               bool `json:"manage_organisations_members,omitempty"`
	AccessOrganisationsBills                 bool `json:"access_organisations_bills,omitempty"`
	AccessOrganisationsCreditCount           bool `json:"access_organisations_credit_count,omitempty"`
	AccessOrganisationsConsumptionStatistics bool `json:"access_organisations_consumption_statistics,omitempty"`
	AccessPersonalInformation                bool `json:"access_personal_information,omitempty"`
	ManagePersonalInformation                bool `json:"manage_personal_information,omitempty"`
	ManageSshKeys                            bool `json:"manage_ssh_keys,omitempty"`
}
