/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// OrganisationView struct for OrganisationView
type OrganisationView struct {
	Id               string `json:"id,omitempty"`
	Name             string `json:"name,omitempty"`
	Description      string `json:"description,omitempty"`
	BillingEmail     string `json:"billingEmail,omitempty"`
	Address          string `json:"address,omitempty"`
	City             string `json:"city,omitempty"`
	Zipcode          string `json:"zipcode,omitempty"`
	Country          string `json:"country,omitempty"`
	Company          string `json:"company,omitempty"`
	VAT              string `json:"VAT,omitempty"`
	Avatar           string `json:"avatar,omitempty"`
	VatState         string `json:"vatState,omitempty"`
	CustomerFullName string `json:"customerFullName,omitempty"`
	CanPay           bool   `json:"canPay,omitempty"`
	CleverEnterprise bool   `json:"cleverEnterprise,omitempty"`
	EmergencyNumber  string `json:"emergencyNumber,omitempty"`
	CanSEPA          bool   `json:"canSEPA,omitempty"`
}
