/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clevercloud

import (
	"encoding/json"
)

// WannabeAddonProviderInfos struct for WannabeAddonProviderInfos
type WannabeAddonProviderInfos struct {
	Name           *string `json:"name,omitempty"`
	Website        *string `json:"website,omitempty"`
	SupportEmail   *string `json:"supportEmail,omitempty"`
	GooglePlusName *string `json:"googlePlusName,omitempty"`
	TwitterName    *string `json:"twitterName,omitempty"`
	AnalyticsId    *string `json:"analyticsId,omitempty"`
	ShortDesc      *string `json:"shortDesc,omitempty"`
	LongDesc       *string `json:"longDesc,omitempty"`
	LogoUrl        *string `json:"logoUrl,omitempty"`
}

// NewWannabeAddonProviderInfos instantiates a new WannabeAddonProviderInfos object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWannabeAddonProviderInfos() *WannabeAddonProviderInfos {
	this := WannabeAddonProviderInfos{}
	return &this
}

// NewWannabeAddonProviderInfosWithDefaults instantiates a new WannabeAddonProviderInfos object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWannabeAddonProviderInfosWithDefaults() *WannabeAddonProviderInfos {
	this := WannabeAddonProviderInfos{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WannabeAddonProviderInfos) SetName(v string) {
	o.Name = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetWebsite() string {
	if o == nil || o.Website == nil {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetWebsiteOk() (*string, bool) {
	if o == nil || o.Website == nil {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasWebsite() bool {
	if o != nil && o.Website != nil {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *WannabeAddonProviderInfos) SetWebsite(v string) {
	o.Website = &v
}

// GetSupportEmail returns the SupportEmail field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetSupportEmail() string {
	if o == nil || o.SupportEmail == nil {
		var ret string
		return ret
	}
	return *o.SupportEmail
}

// GetSupportEmailOk returns a tuple with the SupportEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetSupportEmailOk() (*string, bool) {
	if o == nil || o.SupportEmail == nil {
		return nil, false
	}
	return o.SupportEmail, true
}

// HasSupportEmail returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasSupportEmail() bool {
	if o != nil && o.SupportEmail != nil {
		return true
	}

	return false
}

// SetSupportEmail gets a reference to the given string and assigns it to the SupportEmail field.
func (o *WannabeAddonProviderInfos) SetSupportEmail(v string) {
	o.SupportEmail = &v
}

// GetGooglePlusName returns the GooglePlusName field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetGooglePlusName() string {
	if o == nil || o.GooglePlusName == nil {
		var ret string
		return ret
	}
	return *o.GooglePlusName
}

// GetGooglePlusNameOk returns a tuple with the GooglePlusName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetGooglePlusNameOk() (*string, bool) {
	if o == nil || o.GooglePlusName == nil {
		return nil, false
	}
	return o.GooglePlusName, true
}

// HasGooglePlusName returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasGooglePlusName() bool {
	if o != nil && o.GooglePlusName != nil {
		return true
	}

	return false
}

// SetGooglePlusName gets a reference to the given string and assigns it to the GooglePlusName field.
func (o *WannabeAddonProviderInfos) SetGooglePlusName(v string) {
	o.GooglePlusName = &v
}

// GetTwitterName returns the TwitterName field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetTwitterName() string {
	if o == nil || o.TwitterName == nil {
		var ret string
		return ret
	}
	return *o.TwitterName
}

// GetTwitterNameOk returns a tuple with the TwitterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetTwitterNameOk() (*string, bool) {
	if o == nil || o.TwitterName == nil {
		return nil, false
	}
	return o.TwitterName, true
}

// HasTwitterName returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasTwitterName() bool {
	if o != nil && o.TwitterName != nil {
		return true
	}

	return false
}

// SetTwitterName gets a reference to the given string and assigns it to the TwitterName field.
func (o *WannabeAddonProviderInfos) SetTwitterName(v string) {
	o.TwitterName = &v
}

// GetAnalyticsId returns the AnalyticsId field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetAnalyticsId() string {
	if o == nil || o.AnalyticsId == nil {
		var ret string
		return ret
	}
	return *o.AnalyticsId
}

// GetAnalyticsIdOk returns a tuple with the AnalyticsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetAnalyticsIdOk() (*string, bool) {
	if o == nil || o.AnalyticsId == nil {
		return nil, false
	}
	return o.AnalyticsId, true
}

// HasAnalyticsId returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasAnalyticsId() bool {
	if o != nil && o.AnalyticsId != nil {
		return true
	}

	return false
}

// SetAnalyticsId gets a reference to the given string and assigns it to the AnalyticsId field.
func (o *WannabeAddonProviderInfos) SetAnalyticsId(v string) {
	o.AnalyticsId = &v
}

// GetShortDesc returns the ShortDesc field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetShortDesc() string {
	if o == nil || o.ShortDesc == nil {
		var ret string
		return ret
	}
	return *o.ShortDesc
}

// GetShortDescOk returns a tuple with the ShortDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetShortDescOk() (*string, bool) {
	if o == nil || o.ShortDesc == nil {
		return nil, false
	}
	return o.ShortDesc, true
}

// HasShortDesc returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasShortDesc() bool {
	if o != nil && o.ShortDesc != nil {
		return true
	}

	return false
}

// SetShortDesc gets a reference to the given string and assigns it to the ShortDesc field.
func (o *WannabeAddonProviderInfos) SetShortDesc(v string) {
	o.ShortDesc = &v
}

// GetLongDesc returns the LongDesc field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetLongDesc() string {
	if o == nil || o.LongDesc == nil {
		var ret string
		return ret
	}
	return *o.LongDesc
}

// GetLongDescOk returns a tuple with the LongDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetLongDescOk() (*string, bool) {
	if o == nil || o.LongDesc == nil {
		return nil, false
	}
	return o.LongDesc, true
}

// HasLongDesc returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasLongDesc() bool {
	if o != nil && o.LongDesc != nil {
		return true
	}

	return false
}

// SetLongDesc gets a reference to the given string and assigns it to the LongDesc field.
func (o *WannabeAddonProviderInfos) SetLongDesc(v string) {
	o.LongDesc = &v
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *WannabeAddonProviderInfos) GetLogoUrl() string {
	if o == nil || o.LogoUrl == nil {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WannabeAddonProviderInfos) GetLogoUrlOk() (*string, bool) {
	if o == nil || o.LogoUrl == nil {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *WannabeAddonProviderInfos) HasLogoUrl() bool {
	if o != nil && o.LogoUrl != nil {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *WannabeAddonProviderInfos) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

func (o WannabeAddonProviderInfos) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Website != nil {
		toSerialize["website"] = o.Website
	}
	if o.SupportEmail != nil {
		toSerialize["supportEmail"] = o.SupportEmail
	}
	if o.GooglePlusName != nil {
		toSerialize["googlePlusName"] = o.GooglePlusName
	}
	if o.TwitterName != nil {
		toSerialize["twitterName"] = o.TwitterName
	}
	if o.AnalyticsId != nil {
		toSerialize["analyticsId"] = o.AnalyticsId
	}
	if o.ShortDesc != nil {
		toSerialize["shortDesc"] = o.ShortDesc
	}
	if o.LongDesc != nil {
		toSerialize["longDesc"] = o.LongDesc
	}
	if o.LogoUrl != nil {
		toSerialize["logoUrl"] = o.LogoUrl
	}
	return json.Marshal(toSerialize)
}

type NullableWannabeAddonProviderInfos struct {
	value *WannabeAddonProviderInfos
	isSet bool
}

func (v NullableWannabeAddonProviderInfos) Get() *WannabeAddonProviderInfos {
	return v.value
}

func (v *NullableWannabeAddonProviderInfos) Set(val *WannabeAddonProviderInfos) {
	v.value = val
	v.isSet = true
}

func (v NullableWannabeAddonProviderInfos) IsSet() bool {
	return v.isSet
}

func (v *NullableWannabeAddonProviderInfos) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWannabeAddonProviderInfos(val *WannabeAddonProviderInfos) *NullableWannabeAddonProviderInfos {
	return &NullableWannabeAddonProviderInfos{value: val, isSet: true}
}

func (v NullableWannabeAddonProviderInfos) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWannabeAddonProviderInfos) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
