/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// CouponView struct for CouponView
type CouponView struct {
	Name      string  `json:"name,omitempty"`
	Type      string  `json:"type,omitempty"`
	Value     float32 `json:"value,omitempty"`
	Remaining int64   `json:"remaining,omitempty"`
}
