/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// WannaBuyPackage struct for WannaBuyPackage
type WannaBuyPackage struct {
	PackageId    int64   `json:"packageId,omitempty"`
	Currency     string  `json:"currency,omitempty"`
	Coupon       string  `json:"coupon,omitempty"`
	DropQuantity float32 `json:"dropQuantity,omitempty"`
}
