/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// OAuthApplicationView struct for OAuthApplicationView
type OAuthApplicationView struct {
	Id            string `json:"id,omitempty"`
	Owner         string `json:"owner,omitempty"`
	Name          string `json:"name,omitempty"`
	Description   string `json:"description,omitempty"`
	GitUrl        string `json:"gitUrl,omitempty"`
	DefaultBranch string `json:"defaultBranch,omitempty"`
	Priv          bool   `json:"priv,omitempty"`
}
