/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// InlineObject8 struct for InlineObject8
type InlineObject8 struct {
	Pass  string `json:"pass,omitempty"`
	Pass2 string `json:"pass2,omitempty"`
}
