/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// ApplicationSummary struct for ApplicationSummary
type ApplicationSummary struct {
	Id              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	InstanceType    string `json:"instanceType,omitempty"`
	InstanceVariant string `json:"instanceVariant,omitempty"`
	VariantSlug     string `json:"variantSlug,omitempty"`
	Archived        bool   `json:"archived,omitempty"`
	Homogeneous     bool   `json:"homogeneous,omitempty"`
	VariantLogoUrl  string `json:"variantLogoUrl,omitempty"`
	State           string `json:"state,omitempty"`
	Commit          string `json:"commit,omitempty"`
}
