/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// WannabeOauthApp struct for WannabeOauthApp
type WannabeOauthApp struct {
	Owner string `json:"owner,omitempty"`
	Name  string `json:"name,omitempty"`
}
