/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// PriceWithTaxInfo struct for PriceWithTaxInfo
type PriceWithTaxInfo struct {
	Price         int64  `json:"price,omitempty"`
	TaxFreePrice  int64  `json:"taxFreePrice,omitempty"`
	VatRatio      int64  `json:"vatRatio,omitempty"`
	InvoicedOwner string `json:"invoicedOwner,omitempty"`
}
