/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// BraintreeToken struct for BraintreeToken
type BraintreeToken struct {
	MerchantId string `json:"merchantId,omitempty"`
	Token      string `json:"token,omitempty"`
}
