/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package clevercloud

// LinkedAddonEnvironmentView struct for LinkedAddonEnvironmentView
type LinkedAddonEnvironmentView struct {
	ProviderId string                 `json:"provider_id,omitempty"`
	AddonId    string                 `json:"addon_id,omitempty"`
	AddonName  string                 `json:"addon_name,omitempty"`
	Env        []AddonEnvironmentView `json:"env,omitempty"`
}
