/*
 * Clever-Cloud API
 *
 * Public API for managing Clever-Cloud data and products
 *
 * API version: 1.0.1
 * Contact: support@clever-cloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clevercloud

import (
	"encoding/json"
)

// MFARecoveryCode struct for MFARecoveryCode
type MFARecoveryCode struct {
	Code *string `json:"code,omitempty"`
}

// NewMFARecoveryCode instantiates a new MFARecoveryCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFARecoveryCode() *MFARecoveryCode {
	this := MFARecoveryCode{}
	return &this
}

// NewMFARecoveryCodeWithDefaults instantiates a new MFARecoveryCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFARecoveryCodeWithDefaults() *MFARecoveryCode {
	this := MFARecoveryCode{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *MFARecoveryCode) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MFARecoveryCode) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *MFARecoveryCode) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *MFARecoveryCode) SetCode(v string) {
	o.Code = &v
}

func (o MFARecoveryCode) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	return json.Marshal(toSerialize)
}

type NullableMFARecoveryCode struct {
	value *MFARecoveryCode
	isSet bool
}

func (v NullableMFARecoveryCode) Get() *MFARecoveryCode {
	return v.value
}

func (v *NullableMFARecoveryCode) Set(val *MFARecoveryCode) {
	v.value = val
	v.isSet = true
}

func (v NullableMFARecoveryCode) IsSet() bool {
	return v.isSet
}

func (v *NullableMFARecoveryCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFARecoveryCode(val *MFARecoveryCode) *NullableMFARecoveryCode {
	return &NullableMFARecoveryCode{value: val, isSet: true}
}

func (v NullableMFARecoveryCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFARecoveryCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
